title: RITSEC
author:
  name: RITSEC
  email: eboard@ritsec.club

social_links:
  github: ritsec
  facebook: RITSEC
  twitter: ritsecclub
  instagram: ritsecclub
  youtube: RITSEC
  discord: W7NefdyzHZ

plugins:
  - jekyll-seo-tag
